mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_DATABASE: progresscontrol
rabbitmq:
  image: rabbitmq
  hostname: rabbitmq
  ports:
    - "5672:5672"
    - "15672:15672"
    - "5671:5671"
    - "25672:25672"
    - "4369:4369"
